# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'
trigger:
- master
- switch-react

variables:
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]  
steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm run build
      npm run package
  displayName: 'Build file'


- task: CopyFiles@2
  inputs:
    contents: '**\release**'
    # flattenFolders: true
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: GitHubRelease@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'bryht'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
    assets: |
         $(Build.ArtifactStagingDirectory)/**
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'